# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pr:
  - main

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    sudo apt-get update
    sudo apt-get install npm -y
  displayName: 'npm install npm'
  
- script: |
    sudo npm nstall
    sudo npm run build
  displayName: 'npm audit one'  
  
- script: |
    npm test || true
    
  displayName: 'npm test'



- script: |
    sonar-scanner || true
   
  displayName: 'review code'

- script: |
     sudo apt-get install wget apt-transport-https gnupg lsb-release
     wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
     echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
     sudo apt-get update
     sudo apt-get install trivy
  displayName: 'install trivy'

- script: |
    trivy config Dockerfile
  displayName: 'scan dockerfile'

- script: |
    trivy config k8s
  displayName: 'scan k8s'

- script: |
    docker build -t puneetgo/myapp:v1 .
  displayName: 'building image'

- script: |
    echo $(Docker_Hub_password) | sudo docker login --username $(Docker_Hub_username) --password-stdin
    sudo docker push puneetgo/myapp:v1
  displayName: 'docker login'
  
- task: Docker@2
  displayName: Build and push
  inputs:
   containerRegistry: docker_registry
   command: 'buildAndPush'
   Dockerfile: 'Dockerfile'
   tags: puneetgo/myapp:v1

- task: KubernetesManifest@0
  displayName: Deploy to GKE
  inputs:
    kubernetesServiceConnection: gke_devlopment
    action: deploy
    manifests: |
      k8s/simple/frontend-deployment.yaml
      k8s/simple/service-frontend-lb.yaml